package dal;
// Generated 3-dec-2014 14:24:29 by Hibernate Tools 4.3.1



/**
 * TblLokaal generated by hbm2java
 */
public class TblLokaal  implements java.io.Serializable {


     private Integer id;
     private int lokaalnummer;
     private int gebouw;

    public TblLokaal() {
    }

    public TblLokaal(int lokaalnummer, int gebouw) {
       this.lokaalnummer = lokaalnummer;
       this.gebouw = gebouw;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getLokaalnummer() {
        return this.lokaalnummer;
    }
    
    public void setLokaalnummer(int lokaalnummer) {
        this.lokaalnummer = lokaalnummer;
    }
    public int getGebouw() {
        return this.gebouw;
    }
    
    public void setGebouw(int gebouw) {
        this.gebouw = gebouw;
    }




}


